import type { Metadata } from 'next'

import './globals.css'

export const metadata: Metadata = {
  title: 'Client Intake Form',
  description: 'Generated by Shelen L.',
}
 


export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* Layout UI */}
        {/* Place children where you want to render a page or nested layout */}
        <main>{children}</main>
      </body>
    </html>
  )
}
